# Site settings
title: Luis Pedro Coelho
email: luis@luispedro.org
description: "NGLess is a tools for NGS processing"
baseurl: ""
url: "http://luispedro.github.io/ngless/"
twitter_username: luispedrocoelho
github_username:  luispedro
# Build settings
markdown: kramdown
permalink: pretty

defaults:
    -
        scope:
            path: ""
        values:
            layout: default
